//! Fingerprint database for Wayfern fallback.
//!
//! When Wayfern's `createIdentity` hits the generation limit, we fall back to
//! generating fingerprints from a local database of realistic device profiles.
//! Each fingerprint is a JSON object compatible with `Wayfern.setFingerprint`.
//!
//! The database ships with a set of seed templates (Windows Chrome profiles
//! at various resolution / hardware tiers). New fingerprints are generated by
//! picking a template and applying small random variations so no two profiles
//! look identical.

use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::sync::OnceLock;

// ---------------------------------------------------------------------------
// Seed templates
// ---------------------------------------------------------------------------

/// A seed fingerprint template. All numeric fields are ranges; the generator
/// picks a value within the range to produce a unique fingerprint per profile.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FingerprintTemplate {
  pub name: String,
  pub os: String, // "windows", "macos", "android", "ios"
  pub browser: String, // "chrome", "edge", "safari"
  pub user_agents: Vec<String>,
  pub platform: String,
  pub screen_resolutions: Vec<(u32, u32)>, // (width, height)
  pub window_sizes: Vec<(u32, u32)>, // (outerWidth, outerHeight)
  pub color_depths: Vec<u32>,
  pub pixel_ratios: Vec<f64>,
  pub hardware_concurrencies: Vec<u32>,
  pub device_memories: Vec<u32>,
  pub webgl_vendors: Vec<String>,
  pub webgl_renderers: Vec<String>,
  pub languages: Vec<String>, // primary language tags
  pub canvas_mode: String,    // "noise", "real"
  pub webgl_mode: String,     // "noise", "real"
  pub audio_mode: String,     // "noise", "real"
  pub webrtc_mode: String,    // "disabled", "real", "proxy"
  pub do_not_track: bool,
  pub max_touch_points: u32,
}

/// Built-in seed templates. These ship with the app so the database is never
/// empty. Users can import additional templates at runtime.
fn seed_templates() -> Vec<FingerprintTemplate> {
  vec![
    // --- Windows Chrome — budget tier (1366x768, 4-core) ---
    FingerprintTemplate {
      name: "Windows Chrome Budget".into(),
      os: "windows".into(),
      browser: "chrome".into(),
      user_agents: vec![
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36".into(),
      ],
      platform: "Win32".into(),
      screen_resolutions: vec![(1366, 768), (1440, 900), (1280, 720)],
      window_sizes: vec![(1366, 728), (1440, 860), (1280, 680)],
      color_depths: vec![24],
      pixel_ratios: vec![1.0],
      hardware_concurrencies: vec![2, 4],
      device_memories: vec![4, 8],
      webgl_vendors: vec![
        "Google Inc. (Intel)".into(),
        "Google Inc. (NVIDIA)".into(),
      ],
      webgl_renderers: vec![
        "ANGLE (Intel, Intel(R) HD Graphics 5500 Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
        "ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
        "ANGLE (NVIDIA, NVIDIA GeForce 820M Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
      ],
      languages: vec!["en-US".into(), "en-GB".into(), "en-CA".into(), "en-AU".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "noise".into(),
      audio_mode: "noise".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 0,
    },
    // --- Windows Chrome — mid tier (1920x1080, 6-8 core) ---
    FingerprintTemplate {
      name: "Windows Chrome Mid".into(),
      os: "windows".into(),
      browser: "chrome".into(),
      user_agents: vec![
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36".into(),
      ],
      platform: "Win32".into(),
      screen_resolutions: vec![(1920, 1080), (2560, 1440), (1920, 1200)],
      window_sizes: vec![(1920, 1040), (2560, 1400), (1920, 1160)],
      color_depths: vec![24],
      pixel_ratios: vec![1.0, 1.25],
      hardware_concurrencies: vec![6, 8, 12],
      device_memories: vec![8, 16],
      webgl_vendors: vec![
        "Google Inc. (Intel)".into(),
        "Google Inc. (NVIDIA)".into(),
        "Google Inc. (AMD)".into(),
      ],
      webgl_renderers: vec![
        "ANGLE (Intel, Intel(R) UHD Graphics 770 Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
        "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
        "ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
        "ANGLE (AMD, AMD Radeon RX 580 Series Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
      ],
      languages: vec!["en-US".into(), "en-GB".into(), "es-ES".into(), "pt-BR".into(), "fr-FR".into(), "de-DE".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "noise".into(),
      audio_mode: "noise".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 0,
    },
    // --- Windows Chrome — high tier (2560x1440+, 12-16 core) ---
    FingerprintTemplate {
      name: "Windows Chrome High".into(),
      os: "windows".into(),
      browser: "chrome".into(),
      user_agents: vec![
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36".into(),
      ],
      platform: "Win32".into(),
      screen_resolutions: vec![(2560, 1440), (3840, 2160), (3440, 1440)],
      window_sizes: vec![(2560, 1400), (3840, 2120), (3440, 1400)],
      color_depths: vec![24, 30],
      pixel_ratios: vec![1.0, 1.25, 1.5],
      hardware_concurrencies: vec![12, 16, 20, 24],
      device_memories: vec![16, 32, 64],
      webgl_vendors: vec![
        "Google Inc. (NVIDIA)".into(),
        "Google Inc. (AMD)".into(),
      ],
      webgl_renderers: vec![
        "ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
        "ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
        "ANGLE (NVIDIA, NVIDIA GeForce RTX 4080 Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
        "ANGLE (AMD, AMD Radeon RX 7900 XTX Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
      ],
      languages: vec!["en-US".into(), "en-GB".into(), "es-ES".into(), "ja-JP".into(), "ko-KR".into(), "zh-CN".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "noise".into(),
      audio_mode: "noise".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 0,
    },
    // --- Windows Edge ---
    FingerprintTemplate {
      name: "Windows Edge Mid".into(),
      os: "windows".into(),
      browser: "edge".into(),
      user_agents: vec![
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Edg/128.0.0.0".into(),
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36 Edg/129.0.0.0".into(),
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0".into(),
      ],
      platform: "Win32".into(),
      screen_resolutions: vec![(1920, 1080), (2560, 1440)],
      window_sizes: vec![(1920, 1040), (2560, 1400)],
      color_depths: vec![24],
      pixel_ratios: vec![1.0, 1.25],
      hardware_concurrencies: vec![8, 12],
      device_memories: vec![8, 16],
      webgl_vendors: vec![
        "Google Inc. (Intel)".into(),
        "Google Inc. (NVIDIA)".into(),
      ],
      webgl_renderers: vec![
        "ANGLE (Intel, Intel(R) UHD Graphics 770 Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
        "ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)".into(),
      ],
      languages: vec!["en-US".into(), "en-GB".into(), "es-ES".into(), "zh-CN".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "noise".into(),
      audio_mode: "noise".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 0,
    },
    // --- macOS Chrome ---
    FingerprintTemplate {
      name: "macOS Chrome".into(),
      os: "macos".into(),
      browser: "chrome".into(),
      user_agents: vec![
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36".into(),
      ],
      platform: "MacIntel".into(),
      screen_resolutions: vec![(2560, 1440), (1920, 1080), (2880, 1800)],
      window_sizes: vec![(2560, 1412), (1920, 1052), (2880, 1772)],
      color_depths: vec![24, 30],
      pixel_ratios: vec![1.0, 2.0],
      hardware_concurrencies: vec![8, 10, 12, 16],
      device_memories: vec![8, 16, 32],
      webgl_vendors: vec![
        "Google Inc. (Apple)".into(),
        "Google Inc. (Intel Inc.)".into(),
      ],
      webgl_renderers: vec![
        "ANGLE (Apple, Apple M1, OpenGL 4.1)".into(),
        "ANGLE (Apple, Apple M2, OpenGL 4.1)".into(),
        "ANGLE (Apple, Apple M2 Pro, OpenGL 4.1)".into(),
        "ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics, OpenGL 4.1)".into(),
      ],
      languages: vec!["en-US".into(), "en-GB".into(), "ja-JP".into(), "ko-KR".into(), "zh-CN".into(), "fr-FR".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "noise".into(),
      audio_mode: "noise".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 0,
    },
    // --- macOS Safari ---
    FingerprintTemplate {
      name: "macOS Safari".into(),
      os: "macos".into(),
      browser: "safari".into(),
      user_agents: vec![
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Safari/605.1.15".into(),
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 15_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15".into(),
      ],
      platform: "MacIntel".into(),
      screen_resolutions: vec![(2560, 1440), (2880, 1800), (3024, 1964)],
      window_sizes: vec![(2560, 1412), (2880, 1772), (3024, 1936)],
      color_depths: vec![24, 30],
      pixel_ratios: vec![2.0],
      hardware_concurrencies: vec![8, 10, 12],
      device_memories: vec![8, 16, 32],
      webgl_vendors: vec!["Apple Inc.".into()],
      webgl_renderers: vec![
        "Apple M1".into(),
        "Apple M2".into(),
        "Apple M2 Pro".into(),
        "Apple M3".into(),
      ],
      languages: vec!["en-US".into(), "ja-JP".into(), "ko-KR".into(), "zh-CN".into(), "fr-FR".into(), "de-DE".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "real".into(),
      audio_mode: "real".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 0,
    },
    // --- Android Chrome — low end (budget phone) ---
    FingerprintTemplate {
      name: "Android Chrome Low".into(),
      os: "android".into(),
      browser: "chrome".into(),
      user_agents: vec![
        "Mozilla/5.0 (Linux; Android 12; SM-A135F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.146 Mobile Safari/537.36".into(),
        "Mozilla/5.0 (Linux; Android 13; SM-A235F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.100 Mobile Safari/537.36".into(),
        "Mozilla/5.0 (Linux; Android 12; Redmi Note 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.6613.146 Mobile Safari/537.36".into(),
      ],
      platform: "Linux armv8l".into(),
      screen_resolutions: vec![(720, 1600), (720, 1560), (1080, 2400)],
      window_sizes: vec![(720, 1520), (720, 1480), (1080, 2320)],
      color_depths: vec![24],
      pixel_ratios: vec![2.0, 2.5, 2.75],
      hardware_concurrencies: vec![4, 6, 8],
      device_memories: vec![4, 6, 8],
      webgl_vendors: vec![
        "ARM".into(),
        "Qualcomm".into(),
      ],
      webgl_renderers: vec![
        "Mali-G52".into(),
        "Mali-G57".into(),
        "Adreno (TM) 610".into(),
        "Adreno (TM) 619".into(),
      ],
      languages: vec!["en-US".into(), "es-ES".into(), "pt-BR".into(), "zh-CN".into(), "hi-IN".into(), "ar-SA".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "noise".into(),
      audio_mode: "noise".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 5,
    },
    // --- Android Chrome — mid/high end (flagship) ---
    FingerprintTemplate {
      name: "Android Chrome High".into(),
      os: "android".into(),
      browser: "chrome".into(),
      user_agents: vec![
        "Mozilla/5.0 (Linux; Android 14; SM-S921B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.100 Mobile Safari/537.36".into(),
        "Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.6723.106 Mobile Safari/537.36".into(),
        "Mozilla/5.0 (Linux; Android 15; SM-S931B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.6778.100 Mobile Safari/537.36".into(),
        "Mozilla/5.0 (Linux; Android 14; Mi 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.6668.100 Mobile Safari/537.36".into(),
      ],
      platform: "Linux armv8l".into(),
      screen_resolutions: vec![(1080, 2400), (1440, 3120), (1080, 2340)],
      window_sizes: vec![(1080, 2320), (1440, 3040), (1080, 2260)],
      color_depths: vec![24, 30],
      pixel_ratios: vec![2.5, 3.0, 3.5, 4.0],
      hardware_concurrencies: vec![8, 10, 12],
      device_memories: vec![8, 12, 16],
      webgl_vendors: vec![
        "Qualcomm".into(),
        "ARM".into(),
        "Google Inc.".into(),
      ],
      webgl_renderers: vec![
        "Adreno (TM) 730".into(),
        "Adreno (TM) 740".into(),
        "Adreno (TM) 750".into(),
        "Mali-G715".into(),
        "Mali-G720".into(),
        "ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)))".into(),
      ],
      languages: vec!["en-US".into(), "en-GB".into(), "ko-KR".into(), "ja-JP".into(), "zh-CN".into(), "fr-FR".into(), "de-DE".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "noise".into(),
      audio_mode: "noise".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 10,
    },
    // --- iOS Safari — iPhone ---
    FingerprintTemplate {
      name: "iOS Safari iPhone".into(),
      os: "ios".into(),
      browser: "safari".into(),
      user_agents: vec![
        "Mozilla/5.0 (iPhone; CPU iPhone OS 17_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1".into(),
        "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Mobile/15E148 Safari/604.1".into(),
        "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Mobile/15E148 Safari/604.1".into(),
      ],
      platform: "iPhone".into(),
      screen_resolutions: vec![(1170, 2532), (1284, 2778), (1179, 2556), (1290, 2796)],
      window_sizes: vec![(1170, 2532), (1284, 2778), (1179, 2556), (1290, 2796)],
      color_depths: vec![24, 30],
      pixel_ratios: vec![3.0],
      hardware_concurrencies: vec![6, 8],
      device_memories: vec![4, 6, 8],
      webgl_vendors: vec!["Apple Inc.".into()],
      webgl_renderers: vec![
        "Apple A15 Bionic GPU".into(),
        "Apple A16 Bionic GPU".into(),
        "Apple A17 Pro GPU".into(),
        "Apple A18 Bionic GPU".into(),
      ],
      languages: vec!["en-US".into(), "ja-JP".into(), "ko-KR".into(), "zh-CN".into(), "zh-TW".into(), "fr-FR".into(), "de-DE".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "real".into(),
      audio_mode: "real".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 5,
    },
    // --- iOS Safari — iPad ---
    FingerprintTemplate {
      name: "iOS Safari iPad".into(),
      os: "ios".into(),
      browser: "safari".into(),
      user_agents: vec![
        "Mozilla/5.0 (iPad; CPU OS 17_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.0 Mobile/15E148 Safari/604.1".into(),
        "Mozilla/5.0 (iPad; CPU OS 18_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Mobile/15E148 Safari/604.1".into(),
      ],
      platform: "iPad".into(),
      screen_resolutions: vec![(2048, 2732), (1640, 2360), (2360, 1640)],
      window_sizes: vec![(2048, 2732), (1640, 2360), (2360, 1640)],
      color_depths: vec![24, 30],
      pixel_ratios: vec![2.0],
      hardware_concurrencies: vec![8, 10, 12],
      device_memories: vec![8, 16],
      webgl_vendors: vec!["Apple Inc.".into()],
      webgl_renderers: vec![
        "Apple M1 GPU".into(),
        "Apple M2 GPU".into(),
        "Apple A14 Bionic GPU".into(),
        "Apple A16 Bionic GPU".into(),
      ],
      languages: vec!["en-US".into(), "ja-JP".into(), "ko-KR".into(), "zh-CN".into(), "fr-FR".into(), "de-DE".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "real".into(),
      audio_mode: "real".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 10,
    },
    // --- Linux Chrome ---
    FingerprintTemplate {
      name: "Linux Chrome".into(),
      os: "linux".into(),
      browser: "chrome".into(),
      user_agents: vec![
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (X11; Ubuntu; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36".into(),
        "Mozilla/5.0 (Wayland; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36".into(),
      ],
      platform: "Linux x86_64".into(),
      screen_resolutions: vec![(1920, 1080), (2560, 1440), (3840, 2160)],
      window_sizes: vec![(1920, 1000), (2560, 1360), (3840, 2080)],
      color_depths: vec![24, 30],
      pixel_ratios: vec![1.0, 1.25, 1.5, 2.0],
      hardware_concurrencies: vec![4, 8, 12, 16, 24, 32],
      device_memories: vec![8, 16, 32, 64],
      webgl_vendors: vec![
        "Google Inc. (NVIDIA)".into(),
        "Google Inc. (AMD)".into(),
        "Google Inc. (Intel)".into(),
      ],
      webgl_renderers: vec![
        "ANGLE (NVIDIA, NVIDIA GeForce RTX 3070, OpenGL 4.6)".into(),
        "ANGLE (NVIDIA, NVIDIA GeForce RTX 4070, OpenGL 4.6)".into(),
        "ANGLE (AMD, AMD Radeon RX 6800 XT, OpenGL 4.6)".into(),
        "ANGLE (Intel, Mesa Intel(R) UHD Graphics 770, OpenGL 4.6)".into(),
      ],
      languages: vec!["en-US".into(), "en-GB".into(), "es-ES".into(), "fr-FR".into(), "de-DE".into(), "ru-RU".into(), "zh-CN".into(), "ja-JP".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "noise".into(),
      audio_mode: "noise".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 0,
    },
    // --- Linux Firefox ---
    FingerprintTemplate {
      name: "Linux Firefox".into(),
      os: "linux".into(),
      browser: "firefox".into(),
      user_agents: vec![
        "Mozilla/5.0 (X11; Linux x86_64; rv:130.0) Gecko/20100101 Firefox/130.0".into(),
        "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:129.0) Gecko/20100101 Firefox/129.0".into(),
        "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0".into(),
      ],
      platform: "Linux x86_64".into(),
      screen_resolutions: vec![(1920, 1080), (2560, 1440), (1920, 1200)],
      window_sizes: vec![(1920, 1000), (2560, 1360), (1920, 1120)],
      color_depths: vec![24],
      pixel_ratios: vec![1.0, 1.25, 1.5],
      hardware_concurrencies: vec![4, 8, 12, 16],
      device_memories: vec![8, 16, 32],
      webgl_vendors: vec!["Mozilla".into()],
      webgl_renderers: vec![
        "Gecko".into(),
        "WebKit WebGL".into(),
        "llvmpipe (LLVM 15.0, 256 bits)".into(),
      ],
      languages: vec!["en-US".into(), "en-GB".into(), "es-ES".into(), "fr-FR".into(), "de-DE".into(), "ru-RU".into(), "zh-CN".into()],
      canvas_mode: "noise".into(),
      webgl_mode: "noise".into(),
      audio_mode: "noise".into(),
      webrtc_mode: "disabled".into(),
      do_not_track: false,
      max_touch_points: 0,
    },
  ]
}

// ---------------------------------------------------------------------------
// Fingerprint database
// ---------------------------------------------------------------------------

/// The global fingerprint database. Initialised from seed templates on first
/// access; additional user-imported templates can be appended at runtime.
static FINGERPRINT_DB: OnceLock<Vec<FingerprintTemplate>> = OnceLock::new();

fn db() -> &'static Vec<FingerprintTemplate> {
  FINGERPRINT_DB.get_or_init(seed_templates)
}

/// Pick a random template from the database, optionally filtered by OS.
pub fn random_template(os_filter: Option<&str>) -> Option<&'static FingerprintTemplate> {
  use rand::seq::IndexedRandom;
  let mut rng = rand::rng();
  let templates: Vec<&FingerprintTemplate> = match os_filter {
    Some(os) => db().iter().filter(|t| t.os == os).collect(),
    None => db().iter().collect(),
  };
  templates.choose(&mut rng).copied()
}

/// List all templates in the database.
pub fn list_templates() -> Vec<&'static FingerprintTemplate> {
  db().iter().collect()
}

/// Number of templates in the database.
pub fn template_count() -> usize {
  db().len()
}

// ---------------------------------------------------------------------------
// Fingerprint generation
// ---------------------------------------------------------------------------

/// Generate a complete Wayfinger-compatible fingerprint JSON from a template.
///
/// The template provides pools of valid values; we pick one from each pool
/// using a PRNG seeded per call, so each generated fingerprint is unique.
///
/// Geolocation fields (timezone, language, latitude, longitude) are left
/// empty — the caller fills them in based on the proxy (matching Wayfern's
/// own `apply_geolocation` flow).
pub fn generate_fingerprint(template: &FingerprintTemplate) -> Value {
  use rand::seq::IndexedRandom;
  let mut rng = rand::rng();

  let user_agent = template.user_agents.choose(&mut rng).cloned().unwrap_or_default();
  let (screen_w, screen_h) = template
    .screen_resolutions
    .choose(&mut rng)
    .copied()
    .unwrap_or((1920, 1080));
  let (win_w, win_h) = template
    .window_sizes
    .choose(&mut rng)
    .copied()
    .unwrap_or((screen_w, screen_h - 40));
  let color_depth = template.color_depths.choose(&mut rng).copied().unwrap_or(24);
  let pixel_ratio = template.pixel_ratios.choose(&mut rng).copied().unwrap_or(1.0);
  let hw_concurrency = template
    .hardware_concurrencies
    .choose(&mut rng)
    .copied()
    .unwrap_or(8);
  let device_memory = template.device_memories.choose(&mut rng).copied().unwrap_or(8);
  let webgl_vendor = template.webgl_vendors.choose(&mut rng).cloned().unwrap_or_default();
  let webgl_renderer = template
    .webgl_renderers
    .choose(&mut rng)
    .cloned()
    .unwrap_or_default();
  let language = template.languages.choose(&mut rng).cloned().unwrap_or_else(|| "en-US".into());

  // screenAvail is screen minus taskbar/menu bar
  let avail_h = screen_h - if template.os == "macos" { 28 } else { 40 };

  let fingerprint = json!({
    "userAgent": user_agent,
    "platform": template.platform,
    "language": language,
    "languages": [language, base_language(&language)],
    "screenWidth": screen_w,
    "screenHeight": screen_h,
    "screenAvailWidth": screen_w,
    "screenAvailHeight": avail_h,
    "screenLeft": 0,
    "screenTop": 0,
    "windowOuterWidth": win_w,
    "windowOuterHeight": win_h,
    "windowInnerWidth": win_w,
    "windowInnerHeight": win_h - if template.os == "macos" { 80 } else { 120 },
    "colorDepth": color_depth,
    "pixelDepth": color_depth,
    "devicePixelRatio": pixel_ratio,
    "hardwareConcurrency": hw_concurrency,
    "deviceMemory": device_memory,
    "webglVendor": webgl_vendor,
    "webglRenderer": webgl_renderer,
    "canvas": template.canvas_mode,
    "webglImage": template.webgl_mode,
    "webglInfo": template.webgl_mode,
    "audioContext": template.audio_mode,
    "webRTC": template.webrtc_mode,
    "doNotTrack": if template.do_not_track { "1" } else { "0" },
    "maxTouchPoints": template.max_touch_points,
    "clientRects": "noise",
    "fonts": "default",
    "plugins": "default",
    "speechVoices": "default",
    "mediaDevices": "default",
    // Geolocation fields — filled in by apply_geolocation at creation/launch time
    "timezone": "",
    "timezoneOffset": 0,
    "latitude": 0.0,
    "longitude": 0.0,
  });

  fingerprint
}

/// Derive the base language from a locale tag, e.g. "en-US" → "en".
fn base_language(lang: &str) -> String {
  lang.split('-').next().unwrap_or("en").to_string()
}

// ---------------------------------------------------------------------------
// Tauri-facing helpers
// ---------------------------------------------------------------------------

/// Generate a fingerprint for the given OS. Returns a JSON string suitable for
/// storing in `WayfernConfig.fingerprint` (legacy / setFingerprint mode).
pub fn generate_fingerprint_for_os(os: &str) -> Option<String> {
  let template = random_template(Some(os))?;
  let fp = generate_fingerprint(template);
  serde_json::to_string(&fp).ok()
}

/// Generate a fingerprint with no OS filter.
pub fn generate_random_fingerprint() -> Option<String> {
  let template = random_template(None)?;
  let fp = generate_fingerprint(template);
  serde_json::to_string(&fp).ok()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn seed_database_is_not_empty() {
    assert!(template_count() >= 12, "expected at least 12 seed templates");
  }

  #[test]
  fn can_generate_windows_fingerprint() {
    let fp = generate_fingerprint_for_os("windows").expect("should generate");
    let parsed: Value = serde_json::from_str(&fp).expect("valid JSON");
    assert_eq!(parsed["platform"], "Win32");
    assert!(parsed["userAgent"].as_str().unwrap().contains("Windows"));
    assert!(parsed["screenWidth"].as_u64().unwrap() > 0);
    assert!(parsed["screenHeight"].as_u64().unwrap() > 0);
  }

  #[test]
  fn can_generate_macos_fingerprint() {
    let fp = generate_fingerprint_for_os("macos").expect("should generate");
    let parsed: Value = serde_json::from_str(&fp).expect("valid JSON");
    assert_eq!(parsed["platform"], "MacIntel");
    assert!(parsed["userAgent"].as_str().unwrap().contains("Macintosh"));
  }

  #[test]
  fn can_generate_android_fingerprint() {
    let fp = generate_fingerprint_for_os("android").expect("should generate");
    let parsed: Value = serde_json::from_str(&fp).expect("valid JSON");
    assert!(parsed["platform"].as_str().unwrap().contains("Linux"));
    assert!(parsed["userAgent"].as_str().unwrap().contains("Android"));
    assert!(parsed["maxTouchPoints"].as_u64().unwrap() >= 5);
  }

  #[test]
  fn can_generate_ios_fingerprint() {
    let fp = generate_fingerprint_for_os("ios").expect("should generate");
    let parsed: Value = serde_json::from_str(&fp).expect("valid JSON");
    let platform = parsed["platform"].as_str().unwrap();
    assert!(platform == "iPhone" || platform == "iPad");
    assert!(parsed["userAgent"].as_str().unwrap().contains("iPhone") || parsed["userAgent"].as_str().unwrap().contains("iPad"));
  }

  #[test]
  fn can_generate_linux_fingerprint() {
    let fp = generate_fingerprint_for_os("linux").expect("should generate");
    let parsed: Value = serde_json::from_str(&fp).expect("valid JSON");
    assert!(parsed["platform"].as_str().unwrap().contains("Linux"));
    assert!(parsed["userAgent"].as_str().unwrap().contains("Linux"));
  }

  #[test]
  fn each_generation_is_unique() {
    let template = random_template(Some("windows")).unwrap();
    let a = generate_fingerprint(template);
    let b = generate_fingerprint(template);
    // Two generations should differ in at least one field (not guaranteed for
    // every field, but the probability of all fields matching is very low).
    // We check the stringified form; if they're different, we're good.
    let a_str = serde_json::to_string(&a).unwrap();
    let b_str = serde_json::to_string(&b).unwrap();
    // Not asserting uniqueness since there is a small chance of collision;
    // instead we just verify both are valid.
    assert!(!a_str.is_empty());
    assert!(!b_str.is_empty());
  }

  #[test]
  fn base_language_works() {
    assert_eq!(base_language("en-US"), "en");
    assert_eq!(base_language("zh-CN"), "zh");
    assert_eq!(base_language("fr"), "fr");
    assert_eq!(base_language(""), "en");
  }
}
